#!/bin/bash 

source "${MESA_DIR}/star/test_suite/test_suite_helpers" 

date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S" 
do_one inlist_create_80.00_MJ_10.00_ME_2.00_RJ planet_create_79.97_MJ_2.0_RJ.mod 
date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S" 
echo "FINISHED CREATING PLANET" 
